name: Deploy to EC2

on:
  push:
    branches:
      - 0527
  pull_request:
    branches:
      - 0527

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 2. Create .env file
      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV_VARS }}" >> .env

      # 3. Create remote directory
      - name: Create remote directory
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: mkdir -p /home/ubuntu/srv/ubuntu

      # 4. Copy source
      - name: Copy source via ssh key
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /home/ubuntu/srv/ubuntu/
          remote_host: ${{ secrets.HOST }}
          remote_user: ubuntu
          remote_key: ${{ secrets.KEY }}

      # 5. Run deploy script on EC2
      - name: Run remote deploy.sh
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            sh /home/ubuntu/srv/ubuntu/config/scripts/deploy.sh
